version: '3.1'

services:
  postgres:
    image: postgres:11
    volumes:
      - ./pg/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=todoist-sync
      - POSTGRES_PASSWORD=todoist-sync
      - POSTGRES_DB=todoist-sync
    ports:
    - 5432:5432