---
apiVersion: v1
kind: Service
metadata:
  name: todoist-sync
  labels:
    app: todoist-sync
spec:
  type: NodePort
  selector:
    app: todoist-sync
  ports:
    - protocol: TCP
      port: 3000
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoist-sync
spec:
  selector:
    matchLabels:
      app: todoist-sync
  replicas: 1
  template:
    metadata:
      labels:
        app: todoist-sync
    spec:
      containers:
        - name: todoist-sync
          image: todoist-sync:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 1