all:
  hosts:
    uits-labs:
      ansible_host: deb10.uits-labs.ru
      ansible_user: root
  children:
    wildfly:
      hosts:
        uits-labs:
  vars:
    domain_name: td.uits-labs.ru
    wildfly_path_name: todoist-sync
