apiVersion: v1
kind: Service
metadata:
  name: todoist-sync
  labels:
    app: todoist-sync
spec:
  type: NodePort
  selector:
    app: todoist-sync
  ports:
    - protocol: TCP
      port: 3000
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoist-sync
spec:
  selector:
    matchLabels:
      app: todoist-sync
  replicas: 1
  template:
    metadata:
      labels:
        app: todoist-sync
    spec:
      imagePullSecrets:
        - name: space-registry
      containers:
        - name: todoist-sync
          image: registry.jetbrains.team/p/td-sync/containers/td-sync:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "410m"
            limits:
              memory: "600Mi"
              cpu: "410m"
          ports:
            - containerPort: 3000
          env:
            - name: CONFIG_FILE
              value: "/app/config/application.conf"
            - name: JAVA_OPTS
              value: "-XX:MaxRAMPercentage=75.0 -XX:InitialRAMPercentage=50.0"
          volumeMounts:
            - name: secrets-volume
              mountPath: /app/config
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 3
      volumes:
        - name: config-volume
          configMap:
            name: todoist-sync-config
        - name: secrets-volume
          secret:
            secretName: todoist-sync-secrets
            #push secrets: