name: Clojure Tests

on:
  push:
    branches: [ '**' ]  # Run on all branches
  pull_request:
    branches: [ '**' ]  # Consider PRs to any branch

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # Eclipse Temurin (previously known as AdoptOpenJDK)
        java-version: '11'  # Adjust as needed for your project
        
    - name: Install Leiningen
      uses: DeLaGuardo/setup-clojure@10.2
      with:
        lein: 2.9.8  # Adjust version as needed
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Fetch dependencies
      run: lein deps
      
    - name: Run tests
      run: lein test